### ISSUE TITLE
A question about coordinate transformation

### ISSUE THREAD

**Issue by qiqihaer** [philip-huang/PIXOR#7]
The 3d locations of ground truth boxes are in camera coordinate. In this implementation, coordinate transformation of 3d locations just contains rotation transformation. Is the translation ignored? And in rotation transformation, I think "z=-z" is necessary, which is similar to "y=-y" in datagen.py

**Comment by philip-huang** [comment]
This is an interesting discussion. 
I believe the the KITTI 3D object are labeled in the Velodyne Frame. Since the purpose of the network is to predict Birds' Eye View Bounding box from lidar points, there is no need to transform to camera coordinate frame. 
![Figure from KITTI paper](https://user-images.githubusercontent.com/28571588/60229641-2c5db100-9864-11e9-8597-901bef93bd30.png)

The "z=-z" is a way of aggregating the lidar points into slices of 2D BEV images. The z coordinate is not included in the label as the PIXOR network is not designed to output height information of objects.

For more detail about KITTI dataset: https://journals.sagepub.com/doi/pdf/10.1177/0278364913491297

**Comment by qiqihaer** [comment]
Thank you very much!!! I confused the labels in raw data with the labels in data of 3D object detection. The labels in raw data are actually in the lidar coordinate. And the labels in data of 3D object detection are in camera coordinate.

**Comment by Petros626** [comment]
The kitti annotarions are in camera frame not lidar
