### ISSUE TITLE
CPU and GPU usage 

### ISSUE THREAD

**Issue by sanketgujar** [philip-huang/PIXOR#8]
I am using one GPU to train the model, but it is still using around 10-16G CPU memory. Would you please tell what operations are using so much memory on the CPU.

**Comment by philip-huang** [comment]
Hmm interesting, I have never noticed this before. My guess would be the input preprocessing stuff is using too many threads/memory. This part is handled by the CPU because GPU training is not really the bottleneck (data preprocessing is). 

My suggestion would be to take a look at the input preprocessing stuff and see if you can come up with a better way for your specific application.

**Comment by sanketgujar** [comment]
Thanks for the reply, I did and the preprocessing was the issue. Closing the issue.
